info:
  contact:
    email: kenan3015@gmail.com
    name: AdolphLWQ
    url: https://git.io/tinyurl
  description: TinyURL API Document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: TinyURL Swagger API Docs
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/x-json-stream
      responses:
        "200":
          description: health
          schema:
            type: string
      summary: 健康检查
swagger: "2.0"
